apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmark-service-pod
  template:
    metadata:
      labels:
        app: bookmark-service-pod
    spec:
      containers:
      - name: bookmark-service
        image: madhurtoppo/bookmark-service
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: bookmark-config
                key: postgres_host
          - name: DB_PORT
            valueFrom:
             configMapKeyRef:
               name: bookmark-config
               key: postgres_port
          - name: DB_DATABASE
            valueFrom:
             configMapKeyRef:
               name: bookmark-config
               key: postgres_dbname
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: bookmark-secrets
                key: postgres_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bookmark-secrets
                key: postgres_password